### ISSUE TITLE
Better Method - Tonecurve

### ISSUE THREAD

**Issue by timfuzail** [Kosodrzewinatru/oledify#6]
Setting RGB values from 0 to x to 0 is not the best method to oled-ify. The problem is if you set values till 50 to 0, now there is a sudden shift in visibility of pixels since there are no pixels with values in between 0 and 50. This results in terrible looking gradients.
 I propose a better method - a modified tone curve.
Step 1. Set values from 0 to 50(x) to 0.
Step 2. Let values over 100(2x) remain unchnaged.

Here is what it looks like in photoshop: https://i.ibb.co/L96ttY7/Capture.png

What this will do is 
1. Set values between 0 to 50 to 0.
2. Plot values between 50 to 100 to 0 to 100, resulting in smooth transition from dim part to bright part.

Here is the difference between two methods, right is tonecurve (wasn't a good image to start with): https://i.ibb.co/JkCTBHh/Zombo-Droid-07052020173401.jpg

**Comment by kosodrzewina** [comment]
Thanks for the feedback and sorry for late reply. 

It's my first project that I'm actually trying to maintain and my first approach to native android, so most of the time I'm spending on figuring out how everything works instead of focusing on the most important thing.

My current function responsible for processing images is pretty dumb, so I'll definitely change it to get that smooth transition.
